"""Reporting and CSV helpers for futures/spot HBT runs."""

from __future__ import annotations

from .full_market_runner import (
    SECOND_LEG_FAILURE_STATUSES,
    add_execution_latency_columns,
    add_run_columns,
    attach_entry_signals,
    build_cash_roi_outputs,
    build_entry_exit_frame,
    build_entry_exit_outputs,
    build_locked_roi_outputs,
    build_second_leg_failure_outputs,
    build_stuck_cash_outputs,
    concat_frames,
    count_row_type,
    empty_daily_roi,
    empty_daily_stuck_cash,
    empty_pair_roi_including_open,
    empty_roi_summary,
    empty_stuck_cash_by_pair,
    empty_stuck_cash_summary,
    entry_signal,
    entry_signal_output,
    existing_columns,
    failure_label,
    filled_trade_frame,
    latest_market_frame,
    matching_position,
    ms_to_ns,
    numeric_sum_if_present,
    numeric_value,
    nunique_if_present,
    open_entry_lots,
    open_locked_pnl_by_pair,
    pair_cash_settings_frame,
    run_error_row,
    safe_divide,
    safe_filename,
    second_leg_failed_pairs,
    second_leg_failed_trades,
    second_leg_failure_by_date,
    second_leg_failure_by_pair,
    second_leg_failure_by_status,
    second_leg_failure_market_tick_windows,
    second_leg_failure_overview,
    second_leg_failure_trade_windows,
    sort_by_existing,
    with_time_columns,
    write_csv,
    write_parquet,
    write_entry_exit_by_pair,
)

__all__ = [name for name in globals() if not name.startswith("_")]
