[Stock]
'/mnt/z/ticks_parquet_stock_future/{ldate}.parquet'

[Odd Lot]
'/mnt/z/ticks_parquet_odd_lot/{ldate}.parquet'

[ETF]
'/mnt/z/ticks_parquet_etf/{ldate}.parquet'

[Stock Future]
'/mnt/z/ticks_parquet_stock_future/{ldate}.parquet'